version: '2.12'

services:

  db:
    networks:
      selenoid:
    image: 'mysql:8.0'
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'vk_db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
    # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
    # Opens port 3306 on the container
      - '3306'
    volumes:
      - ./sql_scripts/init.sql:/docker-entrypoint-initdb.d/1.sql
      - ./vk_db:/var/lib/mysql

  mock:
    networks:
      selenoid:
    restart: always
    build: ./mock
    container_name: mock
    ports:
      - '8083:8083'
    expose:
      - '8083'

  app:
    networks:
      selenoid:
    restart: always
    image: 'myapp'
    container_name: app
    volumes:
      - ./app_data:/app/config
    command: /app/myapp --config=/app/config/config.conf
    ports:
      - '8082:8082'
    depends_on:
      - 'db'
      - 'mock'
      - 'selenoid'
    expose:
      - '8082'

  selenoid:
    networks:
      selenoid:
    restart: always
    image: 'aerokube/selenoid:latest'
    container_name: selenoid
    ports:
      - '4444:4444'
    expose:
      - '4444'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./selenoid_data/:/etc/selenoid
    command: ["-conf", "/etc/selenoid/browsers.json", "-container-network", "selenoid"]

  selenoid-ui:
    networks:
      selenoid:
    restart: always
    image: 'aerokube/selenoid-ui:latest'
    container_name: selenoid-ui
    ports:
      - '8084:8080'
    expose:
      - '8084'
    command: ["--selenoid-uri", "http://selenoid:4444"]


networks:
  selenoid:
    external:
      name: selenoid

# Volume names
volumes:
  vk_db:
  app_data:
  selenoid_data:

